#ifndef KEYBOARDS_HANDWIRED_DELL_U473D_TEENSY_LC_CONFIG_H_
#define KEYBOARDS_HANDWIRED_DELL_U473D_TEENSY_LC_CONFIG_H_

#include "../config.h"

#endif /* KEYBOARDS_HANDWIRED_DELL_U473D_TEENSY_LC_CONFIG_H_ */
